In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv(r"C:\Users\Manish\Desktop\datasets\CarPrice_Assignment.csv")

In [5]:
dataset = dataset.drop(['car_ID','symboling','CarName'],axis = 1)

In [6]:
dataset

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
def Encoder(df):
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [11]:
dataset = Encoder(dataset)

In [12]:
dataset

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,0,1,0,2,0,88.6,168.8,64.1,48.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,1,0,1,0,2,0,88.6,168.8,64.1,48.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,0,1,2,2,0,94.5,171.2,65.5,52.4,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,1,0,0,3,1,0,99.8,176.6,66.2,54.3,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,1,0,0,3,0,0,99.4,176.6,66.4,54.3,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1,0,0,3,2,0,109.1,188.8,68.9,55.5,...,141,5,3.78,3.15,9.5,114,5400,23,28,16845.0
201,1,1,0,3,2,0,109.1,188.8,68.8,55.5,...,141,5,3.78,3.15,8.7,160,5300,19,25,19045.0
202,1,0,0,3,2,0,109.1,188.8,68.9,55.5,...,173,5,3.58,2.87,8.8,134,5500,18,23,21485.0
203,0,1,0,3,2,0,109.1,188.8,68.9,55.5,...,145,3,3.01,3.40,23.0,106,4800,26,27,22470.0
204,1,1,0,3,2,0,109.1,188.8,68.9,55.5,...,141,5,3.78,3.15,9.5,114,5400,19,25,22625.0

In [13]:
x = dataset.iloc[:,:-1].values 
y = dataset.iloc[:,-1].values

In [14]:
x

array([[1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.0e+03, 1.9e+01, 2.6e+01],
       ...,
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 5.5e+03, 1.8e+01, 2.3e+01],
       [0.0e+00, 1.0e+00, 0.0e+00, ..., 4.8e+03, 2.6e+01, 2.7e+01],
       [1.0e+00, 1.0e+00, 0.0e+00, ..., 5.4e+03, 1.9e+01, 2.5e+01]])

In [15]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 12629.   , 14869.   ,
       14489.   ,  6989.   ,  8189.   ,  9279.   ,  9279.   ,  5499.   ,
        7099.   ,  6649.   ,  6849.   ,  7349.   ,  7299.   ,  7799.   ,
        7499.   ,  7999.   ,  8249.   ,  8949.   ,  9549.   , 13499.   ,
       14399.   , 13499.   , 17199.   , 19699.   , 18399.   , 11900.   ,
       13200.   , 12440.   , 13860.   , 15580.   , 16900.   , 16695.   ,
       17075.   , 16630.   , 17950.   , 18150.   ,  5572.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8921.   , 12764.   , 22018.   ,
       32528.   , 34028.   , 37028.   , 31400.5  ,  9295.   ,  9895.   ,
       11850.   , 12170.   , 15040.   , 15510.   , 18150.   , 18620.   ,
        5118.   ,  7053.   ,  7603.   ,  7126.   ,  7775.   ,  9960.   ,
        9233.   , 11259.   ,  7463.   , 10198.   ,  8013.   , 11694.   ,
        5348.   ,  6338.   ,  6488.   ,  6918.   ,  7898.   ,  8778.   ,
        6938.   ,  7198.   ,  7898.   ,  7788.   ,  7738.   ,  8358.   ,
        9258.   ,  8058.   ,  8238.   ,  9298.   ,  9538.   ,  8449.   ,
        9639.   ,  9989.   , 11199.   , 11549.   , 17669.   ,  8948.   ,
       10698.   ,  9988.   , 10898.   , 11248.   , 16558.   , 15998.   ,
       15690.   , 15750.   ,  7775.   ,  7975.   ,  7995.   ,  8195.   ,
        8495.   ,  9495.   ,  9995.   , 11595.   ,  9980.   , 13295.   ,
       13845.   , 12290.   , 12940.   , 13415.   , 15985.   , 16515.   ,
       18420.   , 18950.   , 16845.   , 19045.   , 21485.   , 22470.   ,
       22625.   ])

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [18]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6066.96  6795.  ]
 [18611.9  15750.  ]
 [13088.06 15250.  ]
 [-1652.69  5151.  ]
 [10008.38  9995.  ]
 [13690.69 11199.  ]
 [ 6688.84  5389.  ]
 [ 5274.02  7898.  ]
 [21368.56 17199.  ]
 [ 8282.93  6529.  ]
 [14226.78 20970.  ]
 [28775.55 31400.5 ]
 [10078.02 10945.  ]
 [13316.09 18344.  ]
 [ 6280.35  8916.5 ]
 [12228.24  9989.  ]
 [ 9529.8   9295.  ]
 [19285.46 18920.  ]
 [ 9976.64  7895.  ]
 [ 7624.37  6488.  ]
 [10476.85  9959.  ]
 [20083.72 15580.  ]
 [ 9824.5   9895.  ]
 [12843.04 11549.  ]
 [20504.31 15998.  ]
 [ 6695.12  5118.  ]
 [ 7256.92  6938.  ]
 [19891.06 16695.  ]
 [ 8561.08  8358.  ]
 [ 4522.85  5499.  ]
 [ 7789.63  7975.  ]
 [11000.29 12290.  ]
 [17410.96 22018.  ]
 [ 9163.68  8948.  ]
 [ 6092.53  6849.  ]
 [23725.28 41315.  ]
 [11002.55 11595.  ]
 [13785.24 18150.  ]
 [ 6367.66  6377.  ]
 [37321.11 45400.  ]
 [ 4763.48  8916.5 ]]